import auPhoto from "@/assets/hackathon-au.jpg";
import techniversePhoto from "@/assets/hackathon-techniverse.jpg";
import sihPhoto from "@/assets/hackathon-sih.jpg";
import lnitPhoto from "@/assets/hackathon-lnit.jpg";
import adobePhoto from "@/assets/about-5.jpg";
import { HackathonItem } from "./types";

export const HACKATHONS_DATA: HackathonItem[] = [
  {
    id: "techniverse-2k25",
    number: "01",
    title: "Techniverse 2K25",
    tagline: "RGUKT IIIT Srikakulam · 12-Hour Sprint",
    project: "C Command-Line Food Service Engine",
    date: "7–9 MAR 2025 · RGUKT IIIT SRIKAKULAM",
    year: "2025",
    result: "Finalist",
    resultBadge: "VERIFIED FINALIST",
    image: techniversePhoto,
    statement: "Built the low-level backend engine for a command-line food delivery management system in C, handling auth, admin controls, dynamic menu logic, and processing pipelines.",
    description: "Built within a rigorous 12-hour hackathon environment following an 8-problem Data Structures screening round. In addition, finished 4th in the competitive Code Bidding activity representing Team NVIDIA.",
    metrics: [
      { label: "DSA SCREENING", value: "8/8 Solved" },
      { label: "SPRINT DURATION", value: "12 Hours" },
      { label: "CORE LANGUAGE", value: "Pure C" },
      { label: "CODE BIDDING", value: "4th Place (NVIDIA)" },
    ],
    highlights: [
      "Solved all 8 DSA algorithmic screening challenges to secure final round entry",
      "Engineered low-level user authentication & role-based admin controls in pure C",
      "Implemented dynamic menu indexing, ordering queues, and disk persistence",
      "Finished 4th in the high-stakes Code Bidding competitive track",
    ],
    technologies: ["C", "CLI Architecture", "Data Structures", "POSIX File I/O", "Memory Management"],
    category: "LOW-LEVEL SYSTEMS & DSA",
  },
  {
    id: "au-hackathon-2025",
    number: "02",
    title: "AU Hackathon 2025",
    tagline: "Andhra University · Competitive Innovation Challenge",
    project: "LearnYourWay (Adaptive EdTech Engine)",
    date: "AU HACKATHON 2025 · VISAKHAPATNAM",
    year: "2025",
    result: "Final Round",
    resultBadge: "FINAL ROUND STAGE",
    image: auPhoto,
    statement: "Advanced through multi-stage DSA problem solving and technical evaluations to build LearnYourWay (LYW), an adaptive student learning platform.",
    description: "Competitive hackathon hosted at Andhra University. Advanced past intense technical screening and problem-solving rounds into the final presentation stage.",
    metrics: [
      { label: "SCREENING", value: "DSA & Problem Solving" },
      { label: "PRODUCT", value: "LearnYourWay (LYW)" },
      { label: "DOMAIN", value: "Adaptive EdTech" },
      { label: "STATUS", value: "Final Round Selection" },
    ],
    highlights: [
      "Advanced through DSA screening rounds and written technical assessments",
      "Architected adaptive learning paths tailored to individual student speeds",
      "Designed clean modular state flow and interactive learning modules",
      "Delivered final round live technical demonstration before panel",
    ],
    technologies: ["DSA", "EdTech Systems", "React", "State Machines", "System Design"],
    category: "ALGORITHMIC EDTECH & WEB",
  },
  {
    id: "sih-2025",
    number: "03",
    title: "Smart India Hackathon 2025",
    tagline: "Nationwide Innovation Initiative · Govt. of India",
    project: "Autonomous National Problem Solver",
    date: "SIH 2025 · NATIONAL INITIATIVE",
    year: "2025",
    result: "College-Level Finalist",
    resultBadge: "COLLEGE FINALIST",
    image: sihPhoto,
    statement: "Selected as an institutional finalist for the nationwide Smart India Hackathon initiative, designing an intelligent multi-agent pipeline for governance scale.",
    description: "Evaluated across rigorous college-level elimination rounds among dozens of competing teams to qualify as the institutional representative for national review.",
    metrics: [
      { label: "SCOPE", value: "National Initiative" },
      { label: "STAGE", value: "College Finalist" },
      { label: "ARCHITECTURE", value: "AI & Distributed Cloud" },
      { label: "EVALUATION", value: "Top Tier Selection" },
    ],
    highlights: [
      "Cleared institutional preliminary rounds with top technical evaluation scores",
      "Designed an AI-assisted architecture addressing nationwide operational scale",
      "Engineered automated data pipelines with resilient failover design",
      "Selected as college-level finalist for final national round presentation",
    ],
    technologies: ["AI/ML", "Python", "System Design", "Cloud Architecture", "Distributed Data"],
    category: "AI/ML & DISTRIBUTED SCALE",
  },
  {
    id: "lnit-summit-2026",
    number: "04",
    title: "LNIT Summit 2026",
    tagline: "LNIT Summit & Hackathon · Multi-Stage Technical Sprint",
    project: "FinCopilot (AI-Powered Student Finance)",
    date: "LNIT SUMMIT 2026 · HACKATHON",
    year: "2026",
    result: "Final 10 Teams",
    resultBadge: "TOP 10 TEAMS",
    image: lnitPhoto,
    statement: "Engineered FinCopilot, an AI-powered personal financial intelligence copilot for students, finishing among the final 10 teams out of wide competition.",
    description: "Multi-stage technical hackathon. Reached the final 10 teams after demonstrating real-time student budgeting analytics, telemetry, and automated fiscal advice.",
    metrics: [
      { label: "ACHIEVEMENT", value: "Final 10 Teams" },
      { label: "CORE PRODUCT", value: "FinCopilot" },
      { label: "STACK", value: "FastAPI + React + AI" },
      { label: "DATABASE", value: "PostgreSQL / Vector" },
    ],
    highlights: [
      "Ranked among the Top 10 finalist teams out of multi-tier competitive pools",
      "Built FinCopilot with FastAPI backend, micro-services, and interactive UI",
      "Implemented intelligent student spending categorizations & LLM insights",
      "Designed real-time financial telemetry with visual budget forecasting",
    ],
    technologies: ["React", "FastAPI", "PostgreSQL", "Local AI / LLMs", "TailwindCSS"],
    category: "FINTECH & INTELLIGENT AGENTS",
  },
  {
    id: "unstop-adobe-2025",
    number: "05",
    title: "Unstop × Adobe Hackathon",
    tagline: "Unstop × Adobe · Nationwide Creative Engineering Challenge",
    project: "Creative Design Systems & Architectural Challenge",
    date: "UNSTOP × ADOBE 2025",
    year: "2025",
    result: "Final Round Selection",
    resultBadge: "NATIONWIDE SELECTION",
    image: adobePhoto,
    statement: "Competed through nationwide screening challenges to earn final round selection for the high-prestige Unstop × Adobe engineering initiative.",
    description: "Evaluated across competitive algorithmic, product thinking, and creative problem-solving challenges against top engineering candidates across the nation.",
    metrics: [
      { label: "HOST", value: "Unstop × Adobe" },
      { label: "SCOPE", value: "Nationwide Screening" },
      { label: "OUTCOME", value: "Final Round Selection" },
      { label: "FOCUS", value: "Design Systems & Logic" },
    ],
    highlights: [
      "Advanced through competitive nationwide technical screening rounds",
      "Demonstrated multidisciplinary capability combining design systems and algorithms",
      "Crafted intuitive user journey blueprints under rigorous evaluation criteria",
      "Secured prestigious final round qualification status",
    ],
    technologies: ["Design Systems", "UI/UX Architecture", "Problem Solving", "Modern Web", "Creative Tech"],
    category: "DESIGN SYSTEMS & CREATIVE TECH",
  },
];
