import React from 'react';
import { SkillItem, DomainPillar } from './types';
import {
  PythonLogo,
  JavaLogo,
  CppLogo,
  JSLogo,
  TSLogo,
  GoLogo,
  RustLogo,
  ReactLogo,
  DockerLogo,
  PostgreSQLLogo,
  FastAPILogo,
  QiskitLogo,
  PyTorchLogo,
  TailwindLogo,
  LinuxLogo,
  GitLogo,
  ThreejsLogo,
  ViteLogo,
  WebRTCLogo,
  TensorFlowLogo,
  MongoDBLogo,
  GSAPLogo,
  RayLogo,
  CLogo,
  CiscoLogo,
  RaspberryPiLogo,
  LeetCodeLogo,
  SecurityShieldLogo,
  AppleMPSLogo,
} from './TechLogos';
import { Cpu, ShieldCheck, Sparkles, Layers } from 'lucide-react';

export const ALL_SKILLS: SkillItem[] = [
  // 1. LANGUAGES & SYSTEMS
  {
    id: 'python',
    name: 'Python',
    category: 'Core Language',
    domain: 'systems',
    logo: <PythonLogo size={28} />,
    brandColor: '#3776AB',
    brandGlow: 'rgba(55, 118, 171, 0.45)',
    proficiency: 'Mastery',
    experience: '3+ Years',
    badge: 'CORE 3.12',
    projectAssociation: 'Amazon ML Challenge (Rank 135) & Qiskit Algorithms',
    description: 'Primary computational language for distributed ML sweeps, quantum circuit transpilations, and async microservices.',
  },
  {
    id: 'cpp',
    name: 'C++',
    category: 'Systems & CompProg',
    domain: 'systems',
    logo: <CppLogo size={28} />,
    brandColor: '#00599C',
    brandGlow: 'rgba(0, 89, 156, 0.45)',
    proficiency: 'Mastery',
    experience: '3+ Years',
    badge: 'C++20 // STL',
    projectAssociation: 'LeetCode 425+ & High-Performance Computational Algorithms',
    description: 'Competitive programming driver with STL mastery, cache-friendly data structures, and custom memory management.',
  },
  {
    id: 'java',
    name: 'Java',
    category: 'OOP & Concurrency',
    domain: 'systems',
    logo: <JavaLogo size={28} />,
    brandColor: '#EA2D2E',
    brandGlow: 'rgba(234, 45, 46, 0.45)',
    proficiency: 'Mastery',
    experience: '2+ Years',
    badge: 'OOP // JVM',
    projectAssociation: 'Core OOP Engineering & Multithreaded Systems',
    description: 'Enterprise object modeling, concurrent thread scheduling, synchronization primitives, and JVM architecture.',
  },
  {
    id: 'ts',
    name: 'TypeScript',
    category: 'Type Safety',
    domain: 'web',
    logo: <TSLogo size={28} />,
    brandColor: '#3178C6',
    brandGlow: 'rgba(49, 120, 198, 0.45)',
    proficiency: 'Mastery',
    experience: '2+ Years',
    badge: 'STRICT TYPES',
    projectAssociation: 'Full Portfolio Architecture & WebRTC State Engines',
    description: 'Strict type safety with recursive types, discriminated unions, state vector mathematical structures, and clean APIs.',
  },
  {
    id: 'js',
    name: 'JavaScript',
    category: 'Full-Stack Web',
    domain: 'web',
    logo: <JSLogo size={28} />,
    brandColor: '#F7DF1E',
    brandGlow: 'rgba(247, 223, 30, 0.45)',
    proficiency: 'Mastery',
    experience: '3+ Years',
    badge: 'ESNEXT RUNTIME',
    projectAssociation: 'Modern ESNext Engines & Browser Runtime APIs',
    description: 'Event loop mechanics, asynchronous stream processing, Web Audio, and high-framerate DOM manipulation.',
  },
  {
    id: 'go',
    name: 'Go (Golang)',
    category: 'High Concurrency',
    domain: 'systems',
    logo: <GoLogo size={28} />,
    brandColor: '#00ADD8',
    brandGlow: 'rgba(0, 173, 216, 0.45)',
    proficiency: 'Advanced',
    experience: '1+ Years',
    badge: 'GOROUTINES',
    projectAssociation: 'P2P Signaling Servers & Concurrent Mesh Daemons',
    description: 'Lightweight goroutines, CSP channel orchestration, sub-millisecond network routers, and minimal binaries.',
  },
  {
    id: 'rust',
    name: 'Rust',
    category: 'Memory Safe Systems',
    domain: 'systems',
    logo: <RustLogo size={28} />,
    brandColor: '#DEA584',
    brandGlow: 'rgba(222, 165, 132, 0.45)',
    proficiency: 'Advanced',
    experience: '1+ Years',
    badge: 'ZERO-COST',
    projectAssociation: 'Zero-Cost Abstractions & Memory-Safe Cryptographic Modules',
    description: 'Affine ownership type system, lifetime validation, race condition immunity, and high-efficiency native performance.',
  },
  {
    id: 'c',
    name: 'C Language',
    category: 'Low-Level Systems',
    domain: 'systems',
    logo: <CLogo size={28} />,
    brandColor: '#659AD2',
    brandGlow: 'rgba(101, 154, 210, 0.45)',
    proficiency: 'Advanced',
    experience: '2+ Years',
    badge: 'POSIX // KERNEL',
    projectAssociation: 'Embedded Linux & POSIX Memory Management',
    description: 'Pointer arithmetic, direct memory mapping, system calls, bitwise hardware interfacing, and CPU register logic.',
  },
  {
    id: 'leetcode',
    name: 'LeetCode 425+',
    category: 'Competitive DSA',
    domain: 'systems',
    logo: <LeetCodeLogo size={28} />,
    brandColor: '#FFA116',
    brandGlow: 'rgba(255, 161, 22, 0.45)',
    proficiency: 'Mastery',
    experience: 'Continuous',
    badge: '425+ SOLVED',
    projectAssociation: '425+ Problems Solved Across Graphs, DP, Trees & Arrays',
    description: 'Relentless algorithmic problem-solving across dynamic programming, topological graph traversals, and amortized complexity.',
  },

  // 2. QUANTUM COMPUTING & PHYSICS
  {
    id: 'qiskit',
    name: 'IBM Qiskit',
    category: 'Quantum Computing Minor',
    domain: 'quantum',
    logo: <QiskitLogo size={28} />,
    brandColor: '#6929C4',
    brandGlow: 'rgba(105, 41, 196, 0.45)',
    proficiency: 'Mastery',
    experience: 'Academic Minor',
    badge: 'B.TECH MINOR',
    projectAssociation: 'Quantum Computing Minor at Lendi IET & Multi-QPU Compiler',
    description: 'Primary quantum SDK for gate-level synthesis, noise mitigation, state vector tomography, and pulse schedules.',
  },
  {
    id: 'qsvm',
    name: 'Quantum Kernels & QSVM',
    category: 'Quantum Algorithms',
    domain: 'quantum',
    logo: <QiskitLogo size={28} />,
    brandColor: '#00F0FF',
    brandGlow: 'rgba(0, 240, 255, 0.45)',
    proficiency: 'Mastery',
    experience: 'Academic Research',
    badge: 'HILBERT MAP',
    projectAssociation: 'Quantum Kernel Transpilation & High-Dim Hilbert Feature Maps',
    description: 'Mapping classical feature vectors into infinite-dimensional quantum Hilbert spaces via parameterized entanglement circuits.',
  },
  {
    id: 'multi-qpu',
    name: 'Multi-QPU Synthesis',
    category: 'Distributed Compilers',
    domain: 'quantum',
    logo: <QiskitLogo size={28} />,
    brandColor: '#A855F7',
    brandGlow: 'rgba(168, 85, 247, 0.45)',
    proficiency: 'Advanced',
    experience: 'Architecture Prototype',
    badge: 'MIN-CUT GRAPH',
    projectAssociation: 'Distributed Multi-QPU Quantum Circuit Partitioning',
    description: 'Graph-theoretic min-cut graph partitioning to split monolithic quantum circuits across discrete quantum processing units.',
  },
  {
    id: 'bloch',
    name: '3D Bloch Sphere',
    category: 'State Vector Math',
    domain: 'quantum',
    logo: <ThreejsLogo size={28} />,
    brandColor: '#10B981',
    brandGlow: 'rgba(16, 185, 129, 0.45)',
    proficiency: 'Mastery',
    experience: 'Interactive WebGL',
    badge: 'WEBGL 3D MATH',
    projectAssociation: 'Real-Time 3D Bloch Sphere & Quantum State Visualizer',
    description: 'Direct spherical coordinate mapping of complex superposition states |ψ⟩ = cos(θ/2)|0⟩ + e^(iφ)sin(θ/2)|1⟩ in real-time WebGL.',
  },
  {
    id: 'dirac',
    name: 'Dirac Ket Notation',
    category: 'Unitary Operations',
    domain: 'quantum',
    logo: <TSLogo size={28} />,
    brandColor: '#EC4899',
    brandGlow: 'rgba(236, 72, 153, 0.45)',
    proficiency: 'Mastery',
    experience: 'Theoretical & Code',
    badge: '|Ψ⟩ MATRIX',
    projectAssociation: 'Linear Algebraic Matrix Transformations in Hilbert Space',
    description: 'Rigorous unitary gate operations: Pauli X/Y/Z, Hadamard, Phase S/T, CNOT, and arbitrary unitary tensor products.',
  },
  {
    id: 'qiskit-ml',
    name: 'Qiskit ML',
    category: 'Kernel Transpilation',
    domain: 'quantum',
    logo: <QiskitLogo size={28} />,
    brandColor: '#6929C4',
    brandGlow: 'rgba(105, 41, 196, 0.45)',
    proficiency: 'Advanced',
    experience: 'Research Models',
    badge: 'HYBRID VQC',
    projectAssociation: 'Variational Quantum Classifiers (VQC) & Quantum Neural Nets',
    description: 'Hybrid quantum-classical optimization loops coupling classical Adam optimizers with quantum state circuit executions.',
  },
  {
    id: 'epr',
    name: 'EPR Pair Teleportation',
    category: 'Min-Cut Circuit Partition',
    domain: 'quantum',
    logo: <SecurityShieldLogo size={28} />,
    brandColor: '#3B82F6',
    brandGlow: 'rgba(59, 130, 246, 0.45)',
    proficiency: 'Advanced',
    experience: 'Protocol Design',
    badge: 'BELL STATES',
    projectAssociation: 'Quantum Entanglement & Non-Local Teleportation Channels',
    description: 'Entanglement-assisted state transmission protocols utilizing Bell states (|Φ+⟩, |Φ-⟩, |Ψ+⟩, |Ψ-⟩) and LOCC.',
  },

  // 3. MACHINE LEARNING & INTELLIGENT SYSTEMS
  {
    id: 'pytorch',
    name: 'PyTorch',
    category: 'Deep Learning Core',
    domain: 'aiml',
    logo: <PyTorchLogo size={28} />,
    brandColor: '#EE4C2C',
    brandGlow: 'rgba(238, 76, 44, 0.45)',
    proficiency: 'Mastery',
    experience: '2+ Years',
    badge: 'CUDA // MPS',
    projectAssociation: 'Amazon ML Challenge 2026 & Neural Modeling',
    description: 'Dynamic computational graphs, custom loss functions, gradient checkpointing, and GPU accelerated tensor tensors.',
  },
  {
    id: 'tensorflow',
    name: 'TensorFlow',
    category: 'Neural Computation',
    domain: 'aiml',
    logo: <TensorFlowLogo size={28} />,
    brandColor: '#FF6F00',
    brandGlow: 'rgba(255, 111, 0, 0.45)',
    proficiency: 'Advanced',
    experience: '1+ Years',
    badge: 'TF.DATA PIPELINE',
    projectAssociation: 'Keras Functional Architectures & Data Ingestion Pipelines',
    description: 'Static graph execution, model serialization via SavedModel, and TF.data high-throughput ingestion pipelines.',
  },
  {
    id: 'ray',
    name: 'Ray Cluster',
    category: 'Distributed ML Execution',
    domain: 'aiml',
    logo: <RayLogo size={28} />,
    brandColor: '#028CF0',
    brandGlow: 'rgba(2, 140, 240, 0.45)',
    proficiency: 'Advanced',
    experience: 'Production ML',
    badge: 'DISTRIBUTED TUNE',
    projectAssociation: 'Amazon ML Challenge Hyperparameter Optimization',
    description: 'Distributed actor patterns, parallel worker pools, and automated Ray Tune hyperparameter sweeps at cloud scale.',
  },
  {
    id: 'entity-resolution',
    name: 'Entity Resolution',
    category: 'Amazon ML Challenge (Rank 135)',
    domain: 'aiml',
    logo: <PyTorchLogo size={28} />,
    brandColor: '#F59E0B',
    brandGlow: 'rgba(245, 158, 11, 0.45)',
    proficiency: 'Mastery',
    experience: 'National Level',
    badge: 'RANK 135 // TOP 0.2%',
    projectAssociation: 'Rank 135 out of ~75,000 Teams (~0.9863 Macro F0.5)',
    description: 'High-throughput fuzzy entity matching, phonetic encoding, multi-modal feature fusion, and robust post-processing heuristics.',
  },
  {
    id: 'local-llm',
    name: 'Local LLMs & Inference',
    category: 'Edge & Open Models',
    domain: 'aiml',
    logo: <PythonLogo size={28} />,
    brandColor: '#FFD43B',
    brandGlow: 'rgba(255, 212, 59, 0.45)',
    proficiency: 'Mastery',
    experience: 'Active Engineering',
    badge: 'GGUF ON-DEVICE',
    projectAssociation: 'Ollama, GGUF Quantization & Zero-Data-Leakage Agents',
    description: 'On-device open-weights inference (Llama, Mistral, Qwen, DeepSeek), token streaming, and function calling workflows.',
  },
  {
    id: 'apple-mps',
    name: 'Apple MPS Silicon',
    category: 'Hardware Acceleration',
    domain: 'aiml',
    logo: <AppleMPSLogo size={28} />,
    brandColor: '#A2AAAD',
    brandGlow: 'rgba(162, 170, 173, 0.45)',
    proficiency: 'Advanced',
    experience: 'Hardware Optimization',
    badge: 'M-SERIES MPS',
    projectAssociation: 'Metal Performance Shaders on Apple Silicon M-Series',
    description: 'Direct PyTorch MPS backend integration for unified memory tensor acceleration without external GPU cloud overhead.',
  },
  {
    id: 'scikit-learn',
    name: 'Scikit-learn',
    category: 'Classical Benchmarks',
    domain: 'aiml',
    logo: <PythonLogo size={28} />,
    brandColor: '#F97316',
    brandGlow: 'rgba(249, 115, 22, 0.45)',
    proficiency: 'Mastery',
    experience: '2+ Years',
    badge: 'ML PIPELINES',
    projectAssociation: 'Cross-Validation & High-Dimensional Feature Engineering',
    description: 'Random Forests, Gradient Boosted Trees, TF-IDF vectorization, PCA decomposition, and pipeline automation.',
  },

  // 4. DISTRIBUTED PROTOCOLS & NETWORKS
  {
    id: 'fastapi',
    name: 'FastAPI',
    category: 'High Performance Async',
    domain: 'protocols',
    logo: <FastAPILogo size={28} />,
    brandColor: '#009688',
    brandGlow: 'rgba(0, 150, 136, 0.45)',
    proficiency: 'Mastery',
    experience: '2+ Years',
    badge: 'ASYNC ASGI',
    projectAssociation: 'Microservice APIs & High-Throughput WebSocket Hubs',
    description: 'Asynchronous Python ASGI endpoints, Pydantic data validation, OpenAPI autodocumentation, and sub-5ms response times.',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'Relational Database',
    domain: 'protocols',
    logo: <PostgreSQLLogo size={28} />,
    brandColor: '#336791',
    brandGlow: 'rgba(51, 103, 145, 0.45)',
    proficiency: 'Mastery',
    experience: '2+ Years',
    badge: 'ACID RELATIONAL',
    projectAssociation: 'ACID Relational Storage & Index Optimization',
    description: 'Complex relational schemas, B-tree/GIN indexes, JSONB columns, window functions, and connection pooling.',
  },
  {
    id: 'webrtc',
    name: 'WebRTC P2P',
    category: 'Audio/Video Mesh',
    domain: 'protocols',
    logo: <WebRTCLogo size={28} />,
    brandColor: '#10B981',
    brandGlow: 'rgba(16, 185, 129, 0.45)',
    proficiency: 'Mastery',
    experience: 'Architecture Lead',
    badge: 'SUB-10MS P2P',
    projectAssociation: 'OFFLAN Sovereign Peer-to-Peer Zero-Cloud Tunnel',
    description: 'Direct browser-to-browser UDP data channels, SDP offer/answer handshakes, and jitter-free real-time media streams.',
  },
  {
    id: 'websockets',
    name: 'WebSockets & STUN/TURN',
    category: 'Real-time Transport',
    domain: 'protocols',
    logo: <WebRTCLogo size={28} />,
    brandColor: '#00ADD8',
    brandGlow: 'rgba(0, 173, 216, 0.45)',
    proficiency: 'Mastery',
    experience: 'Production Mesh',
    badge: 'STUN // TURN',
    projectAssociation: 'ICE Candidate Gathering & Symmetric NAT Traversal',
    description: 'Full-duplex persistent bidirectional socket tunnels, coturn server deployments, and zero-latency signaling fallback.',
  },
  {
    id: 'crypto',
    name: 'Double Ratchet & X3DH',
    category: 'End-to-End Cryptography',
    domain: 'protocols',
    logo: <SecurityShieldLogo size={28} />,
    brandColor: '#10B981',
    brandGlow: 'rgba(16, 185, 129, 0.45)',
    proficiency: 'Mastery',
    experience: 'Security Implementation',
    badge: 'SIGNAL E2EE',
    projectAssociation: 'Zero-Knowledge E2EE Signal Protocol Cryptography',
    description: 'Continuous Diffie-Hellman key ratchets, ephemeral public keys, forward secrecy, and post-compromise security.',
  },
  {
    id: 'cisco-packet-tracer',
    name: 'Cisco Packet Tracer',
    category: 'Enterprise VLAN Mesh',
    domain: 'protocols',
    logo: <CiscoLogo size={28} />,
    brandColor: '#049FD9',
    brandGlow: 'rgba(4, 159, 217, 0.45)',
    proficiency: 'Advanced',
    experience: 'Network Design',
    badge: 'VLAN MESH',
    projectAssociation: 'Multi-Switch Enterprise VLAN Routing & DHCP Topologies',
    description: 'Designing resilient network topologies, subnets, inter-VLAN routing (Router-on-a-stick), and STP loop prevention.',
  },
  {
    id: 'cisco-ios',
    name: 'Cisco IOS CLI',
    category: 'Router ACL Validator',
    domain: 'protocols',
    logo: <CiscoLogo size={28} />,
    brandColor: '#00BCEB',
    brandGlow: 'rgba(0, 188, 235, 0.45)',
    proficiency: 'Advanced',
    experience: 'Network Engineering',
    badge: 'ROUTER ACL',
    projectAssociation: 'Enterprise Router Access Control Lists & NAT Configurations',
    description: 'Standard and extended Access Control Lists (ACLs), OSPF routing protocols, static NAT pools, and port security.',
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    category: 'NoSQL Document Store',
    domain: 'protocols',
    logo: <MongoDBLogo size={28} />,
    brandColor: '#47A248',
    brandGlow: 'rgba(71, 162, 72, 0.45)',
    proficiency: 'Production',
    experience: '1.5+ Years',
    badge: 'NOSQL BSON',
    projectAssociation: 'Flexible Document Stores & Aggregation Pipelines',
    description: 'Schema-free document persistence, compound indexing, aggregation framework pipelines, and change stream monitors.',
  },

  // 5. DEVOPS, INFRASTRUCTURE & CREATIVE FRONTEND
  {
    id: 'react19',
    name: 'React 19',
    category: 'Component Architecture',
    domain: 'web',
    logo: <ReactLogo size={28} />,
    brandColor: '#61DAFB',
    brandGlow: 'rgba(97, 218, 251, 0.45)',
    proficiency: 'Mastery',
    experience: '3+ Years',
    badge: 'CONCURRENT V19',
    projectAssociation: 'Modern Component Systems & Concurrent Architecture',
    description: 'Transitions, action hooks, ref as prop, resilient state management, and optimized render trees.',
  },
  {
    id: 'threejs',
    name: 'Three.js & WebGL',
    category: '3D Creative Graphics',
    domain: 'web',
    logo: <ThreejsLogo size={28} />,
    brandColor: '#10B981',
    brandGlow: 'rgba(16, 185, 129, 0.45)',
    proficiency: 'Mastery',
    experience: '2+ Years',
    badge: '60 FPS WEBGL',
    projectAssociation: 'Interactive 3D Bloch Spheres & Shader Visualizations',
    description: 'Custom GLSL shaders, camera matrices, particle coordinate systems, and hardware-accelerated 60 FPS pipelines.',
  },
  {
    id: 'gsap',
    name: 'GSAP Animation',
    category: 'ScrollTrigger Physics',
    domain: 'web',
    logo: <GSAPLogo size={28} />,
    brandColor: '#88CE02',
    brandGlow: 'rgba(136, 206, 2, 0.45)',
    proficiency: 'Mastery',
    experience: '2+ Years',
    badge: 'PHYSICS TIMELINE',
    projectAssociation: 'Awwwards-Caliber Editorial Micro-Interactions & Scroll Pinned Cards',
    description: 'ScrollTrigger physics, timeline orchestrations, scrubbed transforms, and frictionless hardware-accelerated easing.',
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS v4',
    category: 'Modern Utility Styling',
    domain: 'web',
    logo: <TailwindLogo size={28} />,
    brandColor: '#06B6D4',
    brandGlow: 'rgba(6, 182, 212, 0.45)',
    proficiency: 'Mastery',
    experience: '3+ Years',
    badge: 'TAILWIND V4',
    projectAssociation: 'Design Systems & Responsive Fluid Layouts',
    description: 'Zero-runtime utility CSS, custom color token palettes, glassmorphism filters, and sub-pixel micro-alignments.',
  },
  {
    id: 'vite',
    name: 'Vite 7',
    category: 'Next-Gen Bundling & DX',
    domain: 'web',
    logo: <ViteLogo size={28} />,
    brandColor: '#646CFF',
    brandGlow: 'rgba(100, 108, 255, 0.45)',
    proficiency: 'Mastery',
    experience: '2+ Years',
    badge: 'VITE 7 ESM',
    projectAssociation: 'Sub-100ms HMR & Modern Production Code Splitting',
    description: 'Native ES modules in dev, Rollup production bundling, tree-shaking, and asset pipeline optimization.',
  },
  {
    id: 'docker',
    name: 'Docker',
    category: 'Containerization & Deploy',
    domain: 'systems',
    logo: <DockerLogo size={28} />,
    brandColor: '#2496ED',
    brandGlow: 'rgba(36, 150, 237, 0.45)',
    proficiency: 'Production',
    experience: '2+ Years',
    badge: 'CONTAINER BUILD',
    projectAssociation: 'Multi-Stage Container Builds & Isolated Microservices',
    description: 'Lightweight multi-stage Dockerfiles, non-root user execution, layer caching, and docker-compose service meshes.',
  },
  {
    id: 'linux',
    name: 'Linux / Unix',
    category: 'Kernel & Shell Sovereignty',
    domain: 'systems',
    logo: <LinuxLogo size={28} />,
    brandColor: '#FCC624',
    brandGlow: 'rgba(252, 198, 36, 0.45)',
    proficiency: 'Mastery',
    experience: '3+ Years',
    badge: 'UNIX SHELL',
    projectAssociation: 'Daily Driver Arch / Ubuntu & Automated Shell Tooling',
    description: 'Bash/Zsh automation, systemd services, SSH tunneling, file permissions, and process management.',
  },
  {
    id: 'git',
    name: 'Git & GitHub',
    category: 'CI/CD & Version Control',
    domain: 'systems',
    logo: <GitLogo size={28} />,
    brandColor: '#F05032',
    brandGlow: 'rgba(240, 80, 50, 0.45)',
    proficiency: 'Mastery',
    experience: '3+ Years',
    badge: 'CI/CD ACTIONS',
    projectAssociation: 'Automated GitHub Actions CI/CD & Atomic Git History',
    description: 'Interactive rebasing, trunk-based development, GitHub Actions CI pipelines, and semver releases.',
  },
  {
    id: 'raspberry-pi',
    name: 'Raspberry Pi 5',
    category: 'Embedded & Self-Hosting',
    domain: 'systems',
    logo: <RaspberryPiLogo size={28} />,
    brandColor: '#C51A4A',
    brandGlow: 'rgba(197, 26, 74, 0.45)',
    proficiency: 'Advanced',
    experience: 'Hardware Lab',
    badge: 'EDGE LAB NODE',
    projectAssociation: 'Home Lab Self-Hosting & Local Edge Services',
    description: 'ARM64 self-hosting, local DNS routing, hardware GPIO interfacing, and resilient always-on edge computing.',
  },
];

export const DOMAIN_PILLARS: DomainPillar[] = [
  {
    number: '01',
    id: 'quantum',
    icon: <Cpu className="w-5 h-5 text-[#A855F7]" />,
    title: 'Quantum & Computational Physics',
    subtitle: 'IBM Qiskit Minor • Multi-QPU Synthesis',
    description: 'Academic minor in Quantum Computing at Lendi IET. Building topology-aware circuit compilers, quantum kernel machines, and 3D interactive Dirac state visualizers.',
    tags: ['IBM QISKIT', 'QSVM KERNELS', '3D BLOCH SPHERE', 'CIRCUIT MIN-CUT'],
    metricLabel: 'PROGRAM',
    metricValue: 'B.TECH MINOR // 3 ARCHIVES',
    accentColor: '#A855F7',
    glowColor: 'rgba(168, 85, 247, 0.4)',
    featuredTechs: ['IBM Qiskit', 'Quantum Kernels & QSVM', 'Multi-QPU Synthesis', '3D Bloch Sphere', 'Dirac Ket Notation'],
  },
  {
    number: '02',
    id: 'protocols',
    icon: <ShieldCheck className="w-5 h-5 text-[#10B981]" />,
    title: 'Distributed Protocols & Security',
    subtitle: 'WebRTC P2P • Zero-Trust Cryptography',
    description: 'Architecting zero-trust, LAN-first sovereign networks. End-to-end encrypted messaging via Double Ratchet + X3DH, P2P media meshes, and Cisco VLAN segmentation.',
    tags: ['WEBRTC P2P', 'OFFLAN TUNNEL', 'DOUBLE RATCHET', 'CISCO IOS CLI'],
    metricLabel: 'LATENCY',
    metricValue: 'SUB-10MS P2P // ZERO CLOUD',
    accentColor: '#10B981',
    glowColor: 'rgba(16, 185, 129, 0.4)',
    featuredTechs: ['WebRTC P2P', 'Double Ratchet & X3DH', 'FastAPI', 'WebSockets & STUN/TURN', 'Cisco Packet Tracer'],
  },
  {
    number: '03',
    id: 'aiml',
    icon: <Sparkles className="w-5 h-5 text-[#F59E0B]" />,
    title: 'Intelligence & High-Dimensional ML',
    subtitle: 'Amazon ML Challenge • Ray Clusters',
    description: 'Rank 135 in Amazon ML Challenge 2026 with ~0.9863 Macro F0.5 score. Distributed hyperparameter sweeps on Ray clusters, phonetic entity resolution, and local Apple MPS inference.',
    tags: ['PYTORCH', 'RAY CLUSTER', 'SCORE ~0.9863', 'APPLE MPS SILICON'],
    metricLabel: 'GLOBAL RANK',
    metricValue: 'RANK 135 // TOP 0.2%',
    accentColor: '#F59E0B',
    glowColor: 'rgba(245, 158, 11, 0.4)',
    featuredTechs: ['PyTorch', 'Ray Cluster', 'Entity Resolution', 'Apple MPS Silicon', 'Local LLMs & Inference'],
  },
  {
    number: '04',
    id: 'web',
    icon: <Layers className="w-5 h-5 text-[#61DAFB]" />,
    title: 'High-Performance Creative Web',
    subtitle: 'React 19 • WebGL Math • GSAP Physics',
    description: 'Crafting bespoke, physics-driven digital interfaces. WebGL 3D math simulations, GSAP ScrollTrigger orchestration, and resilient React 19 + TypeScript component systems.',
    tags: ['REACT 19', 'THREE.JS WEBGL', 'GSAP SCROLLTRIGGER', 'TAILWIND V4'],
    metricLabel: 'RENDER RATE',
    metricValue: '60 FPS WEBGL // 100% TYPED',
    accentColor: '#61DAFB',
    glowColor: 'rgba(97, 218, 251, 0.4)',
    featuredTechs: ['React 19', 'Three.js & WebGL', 'GSAP Animation', 'TypeScript', 'Tailwind CSS v4'],
  },
];

export const PILLAR_KEYWORDS: Record<string, string[]> = {
  '01': ['qiskit', 'quantum', 'bloch', 'dirac', 'epr', 'python'],
  '02': ['golang', 'go', 'rust', 'c language', 'webrtc', 'security', 'cisco', 'websocket', 'tunnel', 'concurrency', 'ratchet', 'fastapi', 'postgresql', 'mongodb'],
  '03': ['pytorch', 'tensorflow', 'ray', 'llm', 'apple mps', 'entity', 'scikit', 'ai', 'numpy'],
  '04': ['react', 'typescript', 'javascript', 'three.js', 'gsap', 'vite', 'tailwind', 'webgl', 'docker', 'linux', 'git', 'raspberry'],
};

// Track subsets for Kinetic Marquees
export const TRACK_1_LANGUAGES = ALL_SKILLS.filter(s => s.domain === 'systems' && ['python', 'cpp', 'java', 'ts', 'js', 'go', 'rust', 'c', 'leetcode'].includes(s.id));
export const TRACK_2_QUANTUM = ALL_SKILLS.filter(s => s.domain === 'quantum');
export const TRACK_3_AIML = ALL_SKILLS.filter(s => s.domain === 'aiml');
export const TRACK_4_PROTOCOLS_WEB = ALL_SKILLS.filter(s => ['protocols', 'web'].includes(s.domain));
